name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

  # release:
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/deploy'
  #   steps:
  #     - name: Release to Heroku.
  #       uses: gonuit/heroku-docker-deploy@v1.3.3
  #       with:
  #         email: ${{ secrets.HEROKU_EMAIL }}
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  #         dockerfile_directory: ./
  #         dockerfile_name: Dockerfile.prod
  #         docker_options: "--no-cache"
  #         process_type: web
